name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Login to GitHub Packages
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/to_do_list:${{ github.ref }} .
          docker push docker.pkg.github.com/${{ github.repository }}/to_do_list:${{ github.ref }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fake Deployment
        run:
        echo "The image to deploy is: docker.pkg.github.com/${{ github.repository }}/to_do_list:${{ github.ref }}"
